version: 1.17.{build}
image: Visual Studio 2017
build:
  verbosity: normal
on_failure:
  - ps: 7zip a .\TestResults TestResults.zip | Push-AppveyorArtifact .\TestResults.zip
artifacts:
  - path: TestResults.zip
    name: TestResults