version: 1.17.{build}
image: Visual Studio 2017
build:
  verbosity: normal
on_failure:
  - ps: $root = Resolve-Path .\TestResults; [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName to-publish }
artifacts:
  - path: TestResults.zip
    name: TestResults