version: 1.17.{build}
image: Visual Studio 2017
build:
  verbosity: normal
on_failure:
  - 7z a .\TestResults TestResults.zip & appveyor PushArtifact .\TestResults.zip
artifacts:
  - path: TestResults.zip
    name: TestResults